# Parameter grid for smooth_layer_thickness functional
smooth_layer_thickness:
  weight: [1e4, 3.16e4, 1e5, 3.16e5, 1e6]  # Different weight values
  dhat: [0.01, 0.0575, 0.105, 0.1525, 0.2]     # Different dhat values

# Base configuration paths (relative to project root)
base_config:
  run_config: "cervix_inflation_EX_V2_original/run_MR_Conradlow.json"
  state_config: "cervix_inflation_EX_V2_original/state_MR_Conradlow.json"
  data_dir: "cervix_inflation_EX_V2_original"

# HPC settings for Ginsburg
hpc:
  walltime: "04:00:00"      # Based on your typical 4-hour interactive sessions
  nodes: 1
  cpus_per_task: 16         # Based on your typical -c 16
  memory: "128GB"           # Based on your typical --mem=128G
  partition: ""             # Leave empty, Ginsburg uses account-based allocation