# Parameter grid for smooth_layer_thickness functional
smooth_layer_thickness:
  weight: [1e3, 3.16e3, 1e4, 3.16e4, 1e5]  # Different weight values
  dhat: [0.001, 0.004, 0.016, 0.064, 0.256]     # Different dhat values

# Base configuration paths (relative to project root)
base_config:
  run_config: "cervix_inflation_EX_V2_original/run_MR_Conradlow.json"
  state_config: "cervix_inflation_EX_V2_original/state_MR_Conradlow.json"
  data_dir: "cervix_inflation_EX_V2_original"

# HPC settings for Ginsburg
hpc:
  walltime: "07:00:00"      # Based on your typical 7-hour interactive sessions
  nodes: 1
  cpus_per_task: 16         # Based on your typical -c 16
  memory: "64GB"           # Based on your typical --mem=128G
  partition: ""             # Leave empty, Ginsburg uses account-based allocation